Minicore-Notas/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Minicore_Notas.Data;
using Minicore_Notas.Models;

namespace Minicore_Notas.Controllers
{
    public class GradesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GradesController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Grades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades.FindAsync(id);
            if (grade == null)
            {
                return NotFound();
            }
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "Name", grade.StudentId);
            return View(grade);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,GradeValue,Date,StudentId")] Grade grade)
        {
            if (id != grade.Id)
            {
                return NotFound();
            }


            try
            {
                _context.Update(grade);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GradeExists(grade.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index", "Home");
        }


        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grade = await _context.Grades.FindAsync(id);
            if (grade != null)
            {
                _context.Grades.Remove(grade);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool GradeExists(int id)
        {
            return _context.Grades.Any(e => e.Id == id);
        }
    }
}

Minicore-Notas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Minicore_Notas.Data;
using Minicore_Notas.Models;
using Minicore_Notas.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Minicore_Notas.Controllers
{

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context, ILogger<HomeController> logger)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {

            //Para crear Grades
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "Name");
            /*retrieve*/
            GradeVM gradeVm = new()
            {
                Grade = new Grade(),
                Student = new Student(),
                Period = new Period(),
                StudentsList = _context.Students.ToList(),
                PeriodsList = _context.Periods.ToList(),
                GradesList = _context.Grades.ToList()

            };


            return View(gradeVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateStudent([Bind("Id,Name")] Student student)
        {

            _context.Add(student);
            await _context.SaveChangesAsync();
            return Redirect(".");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGrade([Bind("Id,Name,GradeValue,Date,StudentId")] Grade grade)
        {
            try
            {
                _context.Add(grade);
                await _context.SaveChangesAsync();
                return Redirect(".");
            }
            catch (Exception e)
            {
                ViewData["StudentId"] = new SelectList(_context.Students, "Id", "Name", grade.StudentId);
                return Redirect(".");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePeriod([Bind("Id,Start,End,Weigh")] Period period)
        {
            try
            {
                _context.Add(period);
                await _context.SaveChangesAsync();

            }
            catch (Exception e)
            {
            }
            return Redirect(".");
        }


        /*ACTION FOR RETRIEVING ALL THE GRADES IN A RANGE OF dates*/

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DefineRange([Bind("Start", "End")] GradeVM gradeVM)
        {

            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "Name");

            var grades = _context.Grades.Where(g => g.Date >= gradeVM.Start && g.Date <= gradeVM.End).ToList();
            var students = _context.Students.ToList();
            var periods = _context.Periods.ToList();
            var gradeVm = new GradeVM
            {
                Promedios = new Dictionary<int, double[]>(),
                Grade = new Grade(),
                GradesList = grades,
                StudentsList = students,
                PeriodsList = periods,
                Start = gradeVM.Start,
                End = gradeVM.End
            };
            foreach (var student in students)
            {
                var promedios = new double[5];
                for (int i = 1; i <= 3; i++)
                {
                    promedios[i - 1] = GetGradesByStudent(student.Id, gradeVM.Start, gradeVM.End, i);
                }
                promedios[3] = promedios[0] + promedios[1] + promedios[2];
                gradeVm.Promedios.Add(student.Id, promedios);

                promedios[4] = (6 - (promedios[0] + promedios[1])) / 0.4;

            }

            return View("Index", gradeVm);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        // METHOD FOR GETTING ALL GRADES WITH STUDENT ID WHERE DATE IS BETWEEN START AND END AND DATE IS BETWEEN START AND END OF PERIOD
        public double GetGradesByStudent(int studentId, DateTime start, DateTime end, int periodId)
        {
            var period = _context.Periods.Find(periodId);
            var lista = _context.Grades.Where(g => g.StudentId == studentId && g.Date >= start && g.Date <= end && g.Date >= period.Start && g.Date <= period.End).ToList();
            if (lista.Count == 0)
            {
                return 0;
            }

            //return the average of the list multiplied by the weigh of the period
            return lista.Average(g => g.GradeValue) * period.Weigh / 100;

            //return lista.Average(g => g.GradeValue);
        }
    }
}

Minicore-Notas/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Minicore_Notas.Data;
using Minicore_Notas.Models;

namespace Minicore_Notas.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }
            try
            {
                _context.Update(student);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentExists(student.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index", "Home");
        }


        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.Id == id);
        }
    }
}

Minicore-Notas/Views/Home/Index.cshtml
@model Minicore_Notas.Models.ViewModel.GradeVM

<div style="border: solid 1px #d3d3d3; background-color: #fefefe; height: 200px;">
    <div class="input-group">

        <div class="container mt-4">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    MiniCore
                </div>
                <div class="card-body">
                    <form asp-action="DefineRange" class="row">
                        <div class="col-5">
                            <div class="form-group">
                                <label asp-for="Start" class="control-label">Fecha Inicio</label>
                                <input type="date" asp-for="Start" class="form-control" />
                                <span asp-validation-for="Start" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-5">
                            <div class="form-group">
                                <label asp-for="End" class="control-label">Fecha Fin</label>
                                <input type="date" asp-for="End" class="form-control" />
                                <span asp-validation-for="End" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-2 md-4 mt-md-0">
                            <button type="submit" class="btn btn-primary">Buscar</button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- TABLA DE REGISTROS -->
            <div class="card mt-4">
                <div class="card-header">
                    Registros
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Estudiante</th>
                                <th>P1</th>
                                <th>P2</th>
                                <th>P3</th>
                                <th>Promedio</th>
                                <th>Mensaje</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.StudentsList)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id) - @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        
                                        @Html.DisplayFor(modelItem => Model.Promedios[item.Id][0])
                                        
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.Promedios[item.Id][1])
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.Promedios[item.Id][2])
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => Model.Promedios[item.Id][3])
                                    </td>
                                    <td>
                                        Debe sacar @Html.DisplayFor(modelItem => Model.Promedios[item.Id][4]) en P3 para aprobar.
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
<div style="display: flex; flex-direction: column; gap: 20px; padding: 10px;">
    <div style="display: flex; justify-content: space-between; gap: 10px;">
        @*ESTUDIANTES*@
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-header bg-danger text-white">
                    Estudiantes
                </div>
                <div class="card-body">
                    <form asp-action="CreateStudent" class="form-inline mb-3">
                        <div class="row">
                            <div class="col">
                                <input asp-for="Student.Name" class="form-control mb-2" placeholder="Nombre del Estudiante" />
                                <span asp-validation-for="Student.Name" class="text-danger"></span>
                            </div>
                                <div class="col">
                                    <button type="submit" class="btn btn-primary mb-1">Crear</button>
                            </div>
                        </div>
                    </form>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.StudentsList)
                            {
                                <tr onclick="window.location.href = '@Url.Action("Edit", "Students", new { id = item.Id })';return false;">
                                    <td >@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td class="btn">@Html.DisplayFor(modelItem => item.Name)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        @*NOTAS*@
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-success text-white">
                    Calificaciones
                </div>
                <div class="card-body">
                    <form asp-action="CreateGrade" class="mb-3">
                        <div class="form-row">
                            <div class="col">
                                <input asp-for="Grade.Name" class="form-control" placeholder="Nombre de la Tarea" />
                                <span asp-validation-for="Grade.Name" class="text-danger"></span>
                            </div>
                            <div class="col">
                                <input asp-for="Grade.GradeValue" class="form-control" placeholder="Valor" />
                                <span asp-validation-for="Grade.GradeValue" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group mt-2">
                            <input asp-for="Grade.Date" class="form-control" type="date" />
                            <span asp-validation-for="Grade.Date" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col">
                                    <select asp-for="Grade.StudentId" class="form-control" asp-items="ViewBag.StudentId"></select>
                                    <span asp-validation-for="Grade.StudentId" class="text-danger"></span>
                                </div>
                                <div class="col">
                                    <button type="submit" class="btn btn-primary">Crear</button>
                                </div>
                            </div>
                            
                        </div>
                        
                    </form>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Valor</th>
                                <th>Fecha</th>
                                <th>Estudiante</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.GradesList)
                            {
                                // each row can be clicked to open the edit action "EditGrade" from the controller "GradesController"
                                <tr  onclick="window.location.href = '@Url.Action("Edit", "Grades", new { id = item.Id })';return false;">
                                    <td class="btn">@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.GradeValue)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Date)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Student.Name)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        @*PROGRESOS*@ @*ESTA OCULTO*@
        <borrador>
        @*
        <div style="border: solid 1px #d3d3d3; background-color: #d1ecf1; width: 30%; ">
            <h2>Progresos</h2>
            <div class="input-group">
                <form asp-action="CreateGrade">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Period.Start" class="control-label"></label>
                        <input asp-for="Period.Start" class="form-control" />
                        <span asp-validation-for="Period.Start" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Period.End" class="control-label"></label>
                        <input asp-for="Period.End" class="form-control" />
                        <span asp-validation-for="Period.End" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Period.Weigh" class="control-label"></label>
                        <input asp-for="Period.Weigh" class="form-control" />
                        <span asp-validation-for="Period.Weigh" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            @*TABLA DE PROGRESOS*@@*
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Period.Start)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Period.End)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Period.Weigh)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.PeriodsList)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Start)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.End)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Weigh)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            *@
        </borrador>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}